security:
    # Configure les hashers de mot de passe pour l'entité User
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Configure les fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Définir les firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # Gestion de la connexion et de la déconnexion
            form_login:
                login_path: app_login
                check_path: app_login  
                username_parameter: _username
                password_parameter: _password
                csrf_token_id: authenticate
                # Optionnel : configure le chemin de redirection après connexion réussie
                # success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                # Optionnel : configure le chemin de redirection après déconnexion
                # target: /login
            # Configure les méthodes d'authentification supplémentaires
            # switch_user: true

    # Contrôle d'accès
    access_control:
        - { path: ^/recette, roles: ROLE_USER }



# Configuration spécifique pour les tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon
